import type { WhatsAppContext } from "./whatsapp"

export interface DiagnosisSolution {
  id: string
  title: string
  what: string
  how: string
  materials: string[]
  duration: string
  factors: string
  /** Señales con las que el cliente reconoce el problema, o razones para intervenir. */
  signals?: { heading: string; items: string[] }
  /** Página de servicio donde está la explicación completa. */
  page?: string
}

// Contenido de referencia para la herramienta "Diagnostica tu artículo".
export const diagnosisSolutions: Record<string, DiagnosisSolution> = {
  "suela-desgastada": {
    id: "suela-desgastada",
    title: "Suela desgastada",
    what: "La suela es la parte inferior del calzado que está en contacto directo con el suelo, por lo que es de los componentes que más se desgasta con el uso.",
    how: "Evaluamos si es posible un cambio de tapa localizado o si se requiere una remonta completa, sustituyendo la suela y preparando, pegando, prensando y perfilando el nuevo componente.",
    materials: ["Crupón", "Crepé", "Neolite", "Caucho expandido"],
    duration: "Entre 2 y 5 días hábiles, según la construcción del calzado.",
    factors:
      "El tipo de construcción, el material original de la suela y el estado de componentes cercanos (cambrión, entresuela) pueden afectar el alcance del trabajo.",
    page: "/servicios/remonta-de-calzado",
  },
  remonta: {
    id: "remonta",
    title: "Remonta de calzado",
    what: "La remonta es un proceso de reconstrucción o sustitución de los componentes de la parte inferior del calzado que se encuentran deteriorados.",
    how: "Diagnóstico, desmontaje, preparación de superficies, selección de materiales, montaje, pegado o costura, prensado, perfilado y acabado.",
    materials: ["Crupón", "Crepé", "Neolite", "Caucho expandido"],
    duration: "Aproximadamente 3 a 6 días hábiles.",
    factors:
      "La construcción del zapato, el material disponible y el nivel de deterioro determinan el alcance de la remonta.",
    page: "/servicios/remonta-de-calzado",
  },
  tapa: {
    id: "tapa",
    title: "Cambio de tapas",
    what: "La tapa es el componente que entra directamente en contacto con el suelo en la parte inferior del tacón.",
    how: "Retiro de la tapa desgastada, inspección, preparación, selección del material, instalación, perfilado y acabado.",
    materials: ["Cauchos de distinta dureza", "Materiales sintéticos para tacón"],
    duration: "Servicio rápido, normalmente el mismo día.",
    factors: "El tipo de tacón y su sistema de fijación determinan el material más adecuado.",
    page: "/servicios/reparacion-de-calzado",
  },
  tacon: {
    id: "tacon",
    title: "Ajuste de tacones y plataformas",
    what: "Corrección de altura, nivelación o perfil de tacones y plataformas.",
    how: "Evaluamos la construcción y el margen de modificación antes de recortar, nivelar, perfilar y dar acabado.",
    materials: ["Materiales propios del tacón original", "Tapas de recambio"],
    duration: "Entre 1 y 3 días hábiles.",
    factors:
      "No todos los tacones o plataformas pueden modificarse sin alterar la estructura del calzado; por eso siempre evaluamos antes de intervenir.",
    page: "/servicios/reparacion-de-calzado",
  },
  "cuello-talonera": {
    id: "cuello-talonera",
    title: "Cambio de cuello y talonera",
    what: "El cuello es la zona superior que rodea la abertura del calzado y roza el tobillo; la talonera es el material interno que protege y estructura el talón.",
    how: "Retiramos el material deteriorado, evaluamos la espuma y estructura interna, seleccionamos el nuevo material, lo cortamos, adaptamos, instalamos y cosemos o fijamos según la construcción.",
    materials: ["Cuero", "Forros textiles", "Espuma de relleno"],
    duration: "Entre 2 y 4 días hábiles.",
    factors:
      "El desgaste por fricción y la pérdida de acolchado son las causas más comunes; repararlo evita que el borde deteriorado siga generando incomodidad.",
    signals: {
      heading: "Problemas habituales",
      items: [
        "Desgaste por fricción",
        "Rotura del material",
        "Forro deteriorado",
        "Espuma expuesta",
        "Costuras abiertas",
        "Pérdida de acolchado",
      ],
    },
    page: "/servicios/reparacion-de-calzado",
  },
  cambrion: {
    id: "cambrion",
    title: "Cambio de cambrión",
    what: "El cambrión es un elemento estructural situado en la zona media del calzado, entre el talón y la parte delantera, que aporta soporte y estabilidad.",
    how: "Diagnóstico, desmontaje necesario, extracción, selección del nuevo elemento, instalación, reconstrucción y acabado.",
    materials: ["Cambriones de distintos materiales según construcción"],
    duration: "Entre 3 y 5 días hábiles.",
    factors:
      "No todos los zapatos incorporan cambrión y su construcción puede variar, por lo que el proceso depende del modelo específico.",
    signals: {
      heading: "Cómo se nota cuando se deteriora",
      items: [
        "Inestabilidad al caminar",
        "Flexión incorrecta del zapato",
        "Ruidos",
        "Deformación de la zona media",
        "Pérdida de soporte",
      ],
    },
    page: "/servicios/reparacion-de-calzado",
  },
  capellada: {
    id: "capellada",
    title: "Reparación de capellada",
    what: "La capellada es la parte superior del calzado que cubre y envuelve el pie.",
    how: "Según el daño, cosemos, reforzamos, sustituimos secciones, restauramos, teñimos o reacondicionamos la zona afectada.",
    materials: ["Cuero", "Sintéticos", "Textiles", "Gamuza", "Nobuck"],
    duration: "Entre 2 y 4 días hábiles.",
    factors:
      "El material de la capellada y la extensión del daño determinan si se repara, refuerza o sustituye una sección.",
    signals: {
      heading: "Daños que solemos encontrar",
      items: [
        "Roturas",
        "Desgarros",
        "Costuras abiertas",
        "Arañazos",
        "Desprendimientos",
        "Deformaciones",
        "Desgaste general",
      ],
    },
    page: "/servicios/reparacion-de-calzado",
  },
  cordones: {
    id: "cordones",
    title: "Cambio de cordones",
    what: "El cordón correcto influye tanto en el ajuste como en la apariencia del calzado.",
    how: "Seleccionamos junto al cliente el color, largo, grosor, material y estilo más adecuado y lo instalamos.",
    materials: ["Cordones planos y redondos", "Distintos materiales y colores"],
    duration: "Servicio inmediato.",
    factors: "El tipo de ojales y el estilo del calzado ayudan a definir el cordón más adecuado.",
    page: "/servicios/reparacion-de-calzado",
  },
  cordonera: {
    id: "cordonera",
    title: "Cambio de cordonera",
    what: "La cordonera es la zona o conjunto de elementos donde se alojan los cordones del calzado.",
    how: "Cambio de ojales o ganchos, reparación de perforaciones, refuerzo o sustitución de los elementos deteriorados.",
    materials: ["Ojales metálicos", "Ganchos", "Refuerzos textiles o de cuero"],
    duration: "Entre 1 y 3 días hábiles.",
    factors: "El material de la capellada alrededor de la cordonera determina el tipo de refuerzo posible.",
    page: "/servicios/reparacion-de-calzado",
  },
  plantilla: {
    id: "plantilla",
    title: "Plantillas",
    what: "Las plantillas prehormadas ya vienen fabricadas con formas determinadas; las plantillas estructurales se diseñan para aportar soporte adicional.",
    how: "Evaluamos el espacio interno, la construcción, la talla y la necesidad específica antes de recomendar el tipo de plantilla.",
    materials: ["Plantillas prehormadas", "Materiales estructurales de soporte"],
    duration: "Servicio inmediato o hasta 2 días si requiere adaptación.",
    factors: "El tipo de calzado y la necesidad puntual del pie definen la plantilla adecuada.",
    page: "/servicios/reparacion-de-calzado",
  },
  pegado: {
    id: "pegado",
    title: "Pegado profesional",
    what: "Pegar un artículo no significa simplemente aplicar pegante: distintos materiales requieren distintos sistemas adhesivos y preparaciones de superficie.",
    how: "Diagnóstico de materiales, limpieza, preparación mecánica y química, aplicación del adhesivo, tiempo de activación, unión, presión, curado y acabado.",
    materials: ["Adhesivos específicos según cuero, caucho, sintético, textil, espuma o EVA"],
    duration: "Entre 1 y 3 días hábiles, según el tiempo de curado del adhesivo.",
    factors:
      "El material, la porosidad, la flexibilidad, la temperatura de trabajo, el tipo de esfuerzo, el área de contacto y la construcción del calzado determinan el adhesivo adecuado.",
    page: "/servicios/pegado-de-calzado",
  },
  lavado: {
    id: "lavado",
    title: "Lavandería especializada",
    what: "Tus tenis y zapatos merecen un lavado especializado, distinto al de una lavadora convencional.",
    how: "Aplicamos lavado superficial o profundo, limpieza de gamuza/nobuck, limpieza y acondicionamiento de cuero, limpieza de suelas y tratamiento de manchas según el caso.",
    materials: ["Productos específicos para cuero, gamuza y textiles"],
    duration: "Entre 1 y 2 días hábiles.",
    factors:
      "El exceso de agua, los residuos de jabón y un secado incorrecto pueden dañar ciertos materiales; por eso evaluamos cada componente antes de lavar.",
    signals: {
      heading: "Por qué no conviene lavarlos en casa",
      items: [
        "Exceso de agua: puede afectar materiales, espumas, adhesivos y estructuras",
        "Residuos de jabón: un enjuague insuficiente deja halos al secarse",
        "Secado incorrecto: la humedad prolongada genera olores y otros problemas",
        "Materiales diferentes: un mismo tenis mezcla cuero, malla, sintético, caucho y espuma, y cada componente requiere un tratamiento distinto",
      ],
    },
    page: "/servicios/lavanderia-de-calzado",
  },
  "tenido-cuero": {
    id: "tenido-cuero",
    title: "Restauración y teñido de cuero",
    what: "Recuperar el color de un artículo de cuero también es recuperar su vida útil, dentro de lo técnicamente posible.",
    how: "Diagnóstico, identificación del material, limpieza, preparación, corrección, igualación de color, aplicación, acabado y protección.",
    materials: ["Tintes para cuero", "Selladores y acabados protectores"],
    duration: "Entre 3 y 5 días hábiles.",
    factors:
      "El estado previo del cuero (grietas, resequedad) y el color solicitado influyen en el resultado. Consulta nuestra política de teñido y riesgos.",
    page: "/servicios/tenido-de-cuero",
  },
  restauracion: {
    id: "restauracion",
    title: "Restauración general",
    what: "Restaurar no significa hacer que un artículo parezca nuevo a cualquier costo, sino recuperar su funcionalidad, apariencia y carácter dentro de lo técnicamente posible.",
    how: "Evaluamos el artículo por completo y combinamos limpieza, reparación estructural, teñido y acabado según lo que necesite.",
    materials: ["Según el material del artículo (cuero, sintético, textil)"],
    duration: "Entre 3 y 7 días hábiles, según el alcance.",
    factors: "El valor sentimental o económico del artículo y su estado de conservación ayudan a definir el alcance.",
    signals: {
      heading: "Por qué vale la pena restaurar",
      items: [
        "Valor económico del artículo",
        "Valor sentimental",
        "Calidad de construcción",
        "Diseño difícil de reemplazar",
        "Materiales que todavía pueden recuperarse",
      ],
    },
    page: "/servicios/tenido-de-cuero",
  },
  cierre: {
    id: "cierre",
    title: "Cambio de cierres",
    what: "Sustitución de cierres metálicos, de nylon o solo del cursor, según el estado del sistema completo.",
    how: "Evaluamos si el problema se soluciona cambiando únicamente el cursor o si se requiere sustituir el cierre completo por uno compatible con la construcción del bolso.",
    materials: ["Cierres metálicos/cobre", "Cierres de nylon", "Cursores de repuesto"],
    duration: "Entre 1 y 3 días hábiles.",
    factors: "El tipo de cierre original y su compatibilidad con el diseño del bolso determinan la solución.",
    page: "/servicios/reparacion-de-bolsos",
  },
  asa: {
    id: "asa",
    title: "Cambio de asas",
    what: "Fabricación o adaptación de nuevas asas en cuero o sintético.",
    how: "Consideramos espesor, color, ancho, largo y sistema de fijación para fabricar o adaptar la nueva asa.",
    materials: ["Cuero", "Materiales sintéticos compatibles"],
    duration: "Entre 2 y 4 días hábiles.",
    factors: "El sistema de fijación original y el peso que debe soportar el asa influyen en el material elegido.",
    page: "/servicios/reparacion-de-bolsos",
  },
  forro: {
    id: "forro",
    title: "Cambio de forro",
    what: "El forro interno protege el contenido del bolso y da estructura a bolsillos y compartimentos.",
    how: "Desmontamos, retiramos el forro deteriorado, tomamos medidas y patrones, cortamos, confeccionamos e instalamos el nuevo forro.",
    materials: ["Telas de forro", "Refuerzos internos"],
    duration: "Entre 3 y 5 días hábiles.",
    factors: "La cantidad de bolsillos, compartimentos y cierres internos afecta el tiempo de confección.",
    signals: {
      heading: "El forro nuevo puede incluir",
      items: ["Bolsillos", "Compartimentos", "Cierres internos", "Refuerzos"],
    },
    page: "/servicios/reparacion-de-bolsos",
  },
  base: {
    id: "base",
    title: "Cambio de base",
    what: "La base del bolso soporta fricción, peso y contacto directo con superficies.",
    how: "Evaluamos la sustitución utilizando un material compatible con el diseño original.",
    materials: ["Cuero", "Materiales reforzados resistentes al roce"],
    duration: "Entre 2 y 4 días hábiles.",
    factors: "El peso habitual que carga el bolso y el material original definen la solución más duradera.",
    page: "/servicios/reparacion-de-bolsos",
  },
  "tapa-bolso": {
    id: "tapa-bolso",
    title: "Cambio de tapa de bolso",
    what: "La tapa es la solapa que cubre la apertura del bolso y protege su contenido.",
    how: "Evaluamos el material y el sistema de fijación para fabricar o adaptar una nueva tapa acorde al diseño.",
    materials: ["Cuero", "Sintéticos compatibles con el diseño original"],
    duration: "Entre 2 y 4 días hábiles.",
    factors: "El sistema de cierre de la tapa (broche, imán, hebilla) condiciona el proceso de adaptación.",
    page: "/servicios/reparacion-de-bolsos",
  },
  herrajes: {
    id: "herrajes",
    title: "Cambio de herrajes",
    what: "Incluye argollas, hebillas, mosquetones, broches, remaches y pasadores.",
    how: "Seleccionamos un herraje compatible no solo visualmente, sino también con la carga y función que desempeña.",
    materials: ["Herrajes metálicos de distintos acabados"],
    duration: "Entre 1 y 3 días hábiles.",
    factors: "La resistencia y el acabado del herraje deben ser compatibles con el uso real del artículo.",
    signals: {
      heading: "Herrajes que trabajamos",
      items: ["Argollas", "Hebillas", "Mosquetones", "Broches", "Remaches", "Pasadores"],
    },
    page: "/servicios/reparacion-de-bolsos",
  },
  costuras: {
    id: "costuras",
    title: "Reparación de costuras",
    what: "Hilo roto, costura abierta, desgarros o uniones debilitadas se solucionan con una reparación específica.",
    how: "Evaluación, preparación, selección de hilo, costura, refuerzo y remate.",
    materials: ["Hilos de alta resistencia"],
    duration: "Entre 1 y 2 días hábiles.",
    factors: "El punto de tensión y la carga habitual del artículo determinan el refuerzo necesario.",
    signals: {
      heading: "Problemas que resolvemos",
      items: [
        "Hilo roto",
        "Costura abierta",
        "Desgarro",
        "Unión debilitada",
        "Asa descosida",
        "Bolsillo desprendido",
      ],
    },
    page: "/servicios/reparacion-de-bolsos",
  },
  "tenido-ropa": {
    id: "tenido-ropa",
    title: "Teñido de prendas de algodón",
    what: "Cambiar el color de una prenda puede darle una segunda vida y evitar reemplazarla.",
    how: "Clasificación, preparación, baño de teñido, control de temperatura y tiempo, fijación, lavado posterior, secado y acabado.",
    materials: ["Colorantes para algodón", "Auxiliares químicos de fijación"],
    duration: "Entre 3 y 5 días hábiles.",
    factors:
      "La composición de la prenda (algodón, poliéster, elastano) puede generar variaciones de color entre materiales. Consulta nuestra política de teñido y riesgos.",
    signals: {
      heading: "Vale la pena teñir cuando",
      items: [
        "La prenda tiene buena calidad",
        "El tejido está en buen estado",
        "El diseño todavía gusta",
        "Tiene valor sentimental",
        "El desgaste está principalmente relacionado con el color",
        "Se desea cambiar completamente su apariencia",
      ],
    },
    page: "/servicios/tenido-de-prendas",
  },
  "restauracion-color": {
    id: "restauracion-color",
    title: "Restauración de color",
    what: "Recuperamos el color original de una prenda o artículo cuando el desgaste está principalmente relacionado con el color.",
    how: "Evaluamos el tejido o material y aplicamos el proceso de teñido o igualación de color más adecuado.",
    materials: ["Colorantes específicos según el material"],
    duration: "Entre 3 y 5 días hábiles.",
    factors: "El teñido no elimina daños estructurales ni manchas permanentes; por eso evaluamos antes de intervenir.",
    page: "/servicios/tenido-de-prendas",
  },
  "recuperacion-apariencia": {
    id: "recuperacion-apariencia",
    title: "Recuperación de apariencia",
    what: "Cuando una prenda conserva buena calidad y construcción, podemos recuperar su apariencia general.",
    how: "Combinamos limpieza, planchado técnico y, si es necesario, teñido para devolverle una apariencia renovada.",
    materials: ["Según el tejido y estado de la prenda"],
    duration: "Entre 2 y 4 días hábiles.",
    factors: "El estado de la fibra y del diseño original determinan qué tan renovada puede quedar la prenda.",
    page: "/servicios/tenido-de-prendas",
  },
  tirantas: {
    id: "tirantas",
    title: "Tirantas de morral",
    what: "Las tirantas soportan todo el peso del morral y concentran la tensión en los puntos donde se unen al cuerpo de la pieza.",
    how: "Evaluamos el anclaje, reforzamos o sustituimos la tiranta y rematamos las costuras de unión para que la carga se reparta de nuevo.",
    materials: ["Cintas de alta resistencia", "Cuero", "Hilos reforzados", "Herrajes de ajuste"],
    duration: "Entre 2 y 4 días hábiles.",
    factors:
      "Los morrales y maletas reciben cargas y tensiones superiores a las de muchos bolsos: buscamos recuperar la resistencia de la zona, no solo cerrar el daño.",
    page: "/servicios/reparacion-de-bolsos",
  },
  correas: {
    id: "correas",
    title: "Reparación de correas",
    what: "La correa es la pieza que permite cargar el artículo al hombro o cruzado y suele fallar en los extremos y en los puntos de ajuste.",
    how: "Reparamos o fabricamos la correa considerando largo, ancho y sistema de fijación, y reforzamos los extremos que reciben la tensión.",
    materials: ["Cuero", "Cintas sintéticas", "Herrajes de ajuste"],
    duration: "Entre 2 y 4 días hábiles.",
    factors: "El peso que carga el artículo y el tipo de herraje definen el material y el refuerzo necesarios.",
    page: "/servicios/reparacion-de-bolsos",
  },
  bolsillos: {
    id: "bolsillos",
    title: "Bolsillos y compartimentos",
    what: "Los bolsillos internos y externos se descosen o se rompen por el uso, y a veces arrastran el forro con ellos.",
    how: "Reparamos la costura, reforzamos la boca del bolsillo o confeccionamos uno nuevo con la tela adecuada, según el daño.",
    materials: ["Telas de forro", "Cierres de repuesto", "Refuerzos internos"],
    duration: "Entre 2 y 4 días hábiles.",
    factors: "Si el forro completo está deteriorado suele convenir cambiarlo antes que reparar bolsillo por bolsillo.",
    page: "/servicios/reparacion-de-bolsos",
  },
  refuerzos: {
    id: "refuerzos",
    title: "Refuerzo de zonas de tensión",
    what: "En morrales y maletas hay zonas que concentran esfuerzo: anclajes de tirantas, esquinas, bases y bocas de cierre.",
    how: "Identificamos el punto que cede, añadimos refuerzo interno o externo compatible con el diseño y rematamos la costura.",
    materials: ["Cuero", "Cintas de refuerzo", "Materiales rígidos para base", "Hilos de alta resistencia"],
    duration: "Entre 2 y 5 días hábiles.",
    factors:
      "Reforzar una zona cambia cómo se reparte la carga: por eso evaluamos toda la pieza y no solo el punto roto.",
    page: "/servicios/reparacion-de-bolsos",
  },
}

export interface DiagnosisCategory {
  id: string
  label: string
  emoji: string
  context: WhatsAppContext
  problems: { id: string; label: string }[]
}

export const diagnosisCategories: DiagnosisCategory[] = [
  {
    id: "calzado",
    label: "Zapatos",
    emoji: "👞",
    context: "calzado",
    problems: [
      { id: "suela-desgastada", label: "Suela desgastada" },
      { id: "remonta", label: "Remonta" },
      { id: "tapa", label: "Tapa" },
      { id: "tacon", label: "Tacón" },
      { id: "cuello-talonera", label: "Cuello / talonera" },
      { id: "cambrion", label: "Cambrión" },
      { id: "capellada", label: "Capellada" },
      { id: "cordones", label: "Cordones" },
      { id: "cordonera", label: "Cordonera" },
      { id: "plantilla", label: "Plantilla" },
      { id: "pegado", label: "Pegado" },
      { id: "lavado", label: "Lavado" },
      { id: "tenido-cuero", label: "Teñido" },
      { id: "restauracion", label: "Restauración" },
    ],
  },
  {
    id: "tenis",
    label: "Tenis",
    emoji: "👟",
    context: "calzado",
    problems: [
      { id: "lavado", label: "Lavado" },
      { id: "suela-desgastada", label: "Suela" },
      { id: "capellada", label: "Capellada" },
      { id: "cuello-talonera", label: "Talonera / cuello" },
      { id: "cordones", label: "Cordones" },
      { id: "plantilla", label: "Plantilla" },
      { id: "pegado", label: "Pegado" },
      { id: "restauracion", label: "Restauración" },
    ],
  },
  {
    id: "botas",
    label: "Botas",
    emoji: "🥾",
    context: "calzado",
    problems: [
      { id: "remonta", label: "Remonta" },
      { id: "suela-desgastada", label: "Suela desgastada" },
      { id: "tapa", label: "Tapa" },
      { id: "cuello-talonera", label: "Cuello / talonera" },
      { id: "capellada", label: "Capellada" },
      { id: "cordonera", label: "Cordonera" },
      { id: "cordones", label: "Cordones" },
      { id: "pegado", label: "Pegado" },
      { id: "tenido-cuero", label: "Teñido de cuero" },
      { id: "restauracion", label: "Restauración" },
    ],
  },
  {
    id: "bolsos",
    label: "Bolsos",
    emoji: "👜",
    context: "bolsos",
    problems: [
      { id: "cierre", label: "Cierre" },
      { id: "asa", label: "Asa" },
      { id: "forro", label: "Forro" },
      { id: "base", label: "Base" },
      { id: "tapa-bolso", label: "Tapa" },
      { id: "herrajes", label: "Herrajes" },
      { id: "costuras", label: "Costuras" },
      { id: "restauracion", label: "Restauración" },
    ],
  },
  {
    id: "morrales",
    label: "Morrales",
    emoji: "🎒",
    context: "bolsos",
    problems: [
      { id: "tirantas", label: "Tirantas" },
      { id: "cierre", label: "Cierre" },
      { id: "costuras", label: "Costuras" },
      { id: "bolsillos", label: "Bolsillos" },
      { id: "forro", label: "Forro" },
      { id: "base", label: "Base" },
      { id: "herrajes", label: "Herrajes" },
      { id: "correas", label: "Correas" },
      { id: "refuerzos", label: "Refuerzos" },
      { id: "restauracion", label: "Restauración" },
    ],
  },
  {
    id: "maletas",
    label: "Maletas y maletines",
    emoji: "💼",
    context: "bolsos",
    problems: [
      { id: "cierre", label: "Cierre" },
      { id: "asa", label: "Asa" },
      { id: "tirantas", label: "Tirantas" },
      { id: "correas", label: "Correas" },
      { id: "forro", label: "Forro" },
      { id: "base", label: "Base" },
      { id: "herrajes", label: "Herrajes" },
      { id: "costuras", label: "Costuras" },
      { id: "refuerzos", label: "Refuerzos" },
      { id: "restauracion", label: "Restauración" },
    ],
  },
  {
    id: "prendas",
    label: "Prendas",
    emoji: "👕",
    context: "ropa",
    problems: [
      { id: "tenido-ropa", label: "Teñido" },
      { id: "restauracion-color", label: "Restauración de color" },
      { id: "recuperacion-apariencia", label: "Recuperación de apariencia" },
    ],
  },
  {
    id: "cuero",
    label: "Artículos de cuero",
    emoji: "🧥",
    context: "cuero",
    problems: [
      { id: "tenido-cuero", label: "Teñido de cuero" },
      { id: "restauracion", label: "Restauración" },
      { id: "restauracion-color", label: "Restauración de color" },
      { id: "costuras", label: "Costuras" },
      { id: "cierre", label: "Cierre" },
      { id: "herrajes", label: "Herrajes" },
    ],
  },
]
